### PR TITLE
Crud operations

### PR DESCRIPTION
**Pull request by rugwizangoga**
# Implemented CRUD operations

- Created a new JavaScript file for the new functionality
- Implemented a function for adding a new task (add a new element to the array).
- Implemented a function for deleting a task (remove an element from the array).
- Implemented a function for editing task descriptions.
- All changes to the To Do List are saved in local storage.

### CODE REVIEW

**Review by frank1738 — APPROVED** [review]
Hi @rugwizangoga , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

YesYouAreGIF (2)

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ App works as expected 👍 
✅ Good PR Description 👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by rugwizangoga** [comment]
hello @frank1738, 
can you please help me.

I accidentally submitted this pull request to the wrong exercise and I couldn't undo it because if was already claimed for review on the other end and now  I am stuck with this review pending that I can't do anything about. the exercise is day 4 exercise called   To Do list: interactive list.

**Comment by rugwizangoga** [comment]
please help me if you can

**Comment by ghost** [comment]
> please help me if you can

Hello @rugwizangoga ., As I can see, in this milestone you implemented the `To Do list: add & remove`  exercise. I did not see any implementation of `Do list: interactive list.`.

**Comment by rugwizangoga** [comment]
@frank1738 ,
yes I did not do that which is I need you to help me cancel that mistaken submission so that I can submit the real pull request for that project. I am blocked by the pending review yet that submission is a mistake. please help me

**Comment by rugwizangoga** [comment]
and cancel it

**Comment by ghost** [comment]
> @frank1738 , yes I did not do that which is I need you to help me cancel that mistaken submission so that I can submit the real pull request for that project. I am blocked by the pending review yet that submission is a mistake. please help me

Kindly email the student success ` success@microverse.org` clearly explaining the issue.

**Comment by ghost** [comment]
> @frank1738 , yes I did not do that which is I need you to help me cancel that mistaken submission so that I can submit the real pull request for that project. I am blocked by the pending review yet that submission is a mistake. please help me

But I believe that if the status is `pending`, It will soon be reviewed and invalidated. So you will still be able to submit your project

**Comment by rugwizangoga** [comment]
ok

**Comment by peterrobert** [comment]
### INVALID REQUEST

- [ ] It seems you have submitted an already approved pull request.

**Pull request merged**
